import importlib.util
import json
import os
from pathlib import Path
import unittest
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location("toolchain_check", ROOT / "tools/toolchain/check.py")
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


class ToolchainTest(unittest.TestCase):
    def setUp(self):
        self.manifest = json.loads((ROOT / "tools/toolchain/manifest.json").read_text())

    def test_locks_and_assets(self):
        MODULE.check_locks(self.manifest)

    def test_canonicalization_removes_generator_and_normalizes_lines(self):
        raw = b'<!-- Generated by graphviz version 15.1.1 (x) -->\r\n<svg>ok</svg>\r\n'
        self.assertEqual(MODULE.canonical_svg(raw), b"<svg>ok</svg>\n")

    def test_version_drift_is_actionable(self):
        changed = json.loads(json.dumps(self.manifest))
        changed["versions"]["python"] = "0.0.0"
        with mock.patch.dict(os.environ, changed["environment"], clear=False):
            with self.assertRaisesRegex(MODULE.Failure, "TC3906.*python"):
                MODULE.check_environment(changed)

    def test_environment_drift_is_actionable(self):
        with mock.patch.dict(os.environ, self.manifest["environment"], clear=False):
            os.environ["TZ"] = "Europe/Berlin"
            with self.assertRaisesRegex(MODULE.Failure, "TC3907.*TZ"):
                MODULE.check_environment(self.manifest)

    def test_font_drift_is_actionable(self):
        changed = json.loads(json.dumps(self.manifest))
        changed["graphviz"]["font_sha256"] = "0" * 64
        with self.assertRaisesRegex(MODULE.Failure, "TC3905.*font digest"):
            MODULE.check_locks(changed)

    def test_fixture_reproduces(self):
        MODULE.render_fixture(self.manifest)


if __name__ == "__main__":
    unittest.main()
