#!/usr/bin/env python3
"""Verify and reproduce the Task 0037-39 rendering toolchain."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / "tools/toolchain/manifest.json"


class Failure(Exception):
    pass


def fail(rule, detail):
    raise Failure(f"{rule}: {detail}")


def run(command, env=None):
    try:
        return subprocess.run(command, cwd=ROOT, env=env, check=True, text=True,
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE).stdout
    except (OSError, subprocess.CalledProcessError) as exc:
        fail("TC3901", f"command failed: {' '.join(command)} ({exc})")


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def version(command, pattern):
    try:
        completed = subprocess.run(command, cwd=ROOT, check=True, text=True,
                                   stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except (OSError, subprocess.CalledProcessError) as exc:
        fail("TC3901", f"version command failed: {' '.join(command)} ({exc})")
    output = completed.stdout + completed.stderr
    match = re.search(pattern, output)
    if not match:
        fail("TC3902", f"cannot parse version from {command[0]} output: {output.strip()!r}")
    return match.group(1)


def canonical_svg(data):
    text = data.decode("utf-8").replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"<!-- Generated by graphviz version .*?-->\n?", "", text, flags=re.DOTALL)
    return (text.rstrip() + "\n").encode("utf-8")


def check_locks(manifest):
    requirements = (ROOT / "requirements.lock").read_text(encoding="utf-8")
    if "ruamel.yaml==0.18.14" not in requirements or "--hash=sha256:" not in requirements:
        fail("TC3903", "requirements.lock is not exact and hash-pinned")
    package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
    lock = json.loads((ROOT / "package-lock.json").read_text(encoding="utf-8"))
    wanted = package.get("devDependencies", {})
    locked = lock.get("packages", {}).get("", {}).get("devDependencies", {})
    if wanted != locked or any(v.startswith(("^", "~", ">", "<", "*")) for v in wanted.values()):
        fail("TC3904", "package.json dependencies are not exact or disagree with package-lock.json")
    if lock.get("lockfileVersion") != 3:
        fail("TC3904", "package-lock.json lockfileVersion must be 3")
    for path in (manifest["graphviz"]["font_file"], manifest["graphviz"]["font_license"]):
        if not (ROOT / path).is_file():
            fail("TC3905", f"tracked font asset is missing: {path}")
    if sha256(ROOT / manifest["graphviz"]["font_file"]) != manifest["graphviz"]["font_sha256"]:
        fail("TC3905", "font digest drift")
    if sha256(ROOT / manifest["graphviz"]["font_license"]) != manifest["graphviz"]["font_license_sha256"]:
        fail("TC3905", "font license digest drift")


def check_environment(manifest):
    observed = {
        "python": ".".join(map(str, sys.version_info[:3])),
        "node": version(["node", "--version"], r"v([0-9.]+)"),
        "npm": version(["npm", "--version"], r"([0-9.]+)"),
        "graphviz": version(["dot", "-V"], r"version ([0-9.]+)"),
    }
    for name, expected in manifest["versions"].items():
        if name == "ruamel.yaml":
            continue
        if observed.get(name) != expected:
            fail("TC3906", f"unsupported {name}: expected {expected}, got {observed.get(name)}")
    for name, expected in manifest["environment"].items():
        if os.environ.get(name) != expected:
            fail("TC3907", f"environment drift for {name}: expected {expected!r}, got {os.environ.get(name)!r}")
    return observed


def parser_probe(python=sys.executable):
    code = "from ruamel.yaml import YAML; y=YAML(typ='safe'); assert y.load('answer: 42')['answer'] == 42; import ruamel.yaml; print(ruamel.yaml.__version__)"
    got = run([str(python), "-c", code]).strip()
    if got != "0.18.14":
        fail("TC3908", f"parser version drift: expected 0.18.14, got {got}")


def render_fixture(manifest):
    source = ROOT / "_src/tests/fixtures/0037-39/canonical.dot"
    expected = ROOT / "_src/tests/fixtures/0037-39/canonical.svg"
    if not source.is_file() or not expected.is_file():
        fail("TC3909", "canonical DOT/SVG fixture is missing")
    env = os.environ.copy()
    env["GDFONTPATH"] = str(ROOT / manifest["graphviz"]["font_path"])
    command = [manifest["graphviz"]["executable"], *manifest["graphviz"]["flags"], str(source)]
    actual = canonical_svg(run(command, env=env).encode("utf-8"))
    if actual != expected.read_bytes():
        fail("TC3910", f"canonical SVG drift: expected sha256 {sha256(expected)}, got {hashlib.sha256(actual).hexdigest()}")
    with tempfile.TemporaryDirectory() as temp:
        first = Path(temp) / "first.svg"
        first.write_bytes(actual)
        second = canonical_svg(run(command, env=env).encode("utf-8"))
        if first.read_bytes() != second:
            fail("TC3910", "repeated canonical rendering is not byte-identical")
    return hashlib.sha256(actual).hexdigest()


def clean_install(destination):
    venv = Path(destination) / "venv"
    run([sys.executable, "-m", "venv", str(venv)])
    pip = venv / "bin/pip"
    run([str(pip), "install", "--require-hashes", "--only-binary=:all:", "-r", "requirements.lock"])
    return venv / "bin/python"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--clean-install", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    try:
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        check_locks(manifest)
        observed = check_environment(manifest)
        temporary = tempfile.TemporaryDirectory() if args.clean_install else None
        python = clean_install(temporary.name) if temporary else sys.executable
        parser_probe(python)
        digest = render_fixture(manifest)
        if temporary:
            temporary.cleanup()
        result = {"status": "PASS", "task_id": "0037-39", "observed": observed,
                  "fixture_sha256": digest, "clean_install": args.clean_install}
        print(json.dumps(result, sort_keys=True) if args.json else "0037-39 toolchain PASS")
        return 0
    except Failure as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
